services:
  api:
    build: .
    container_name: ecommerce-api
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://ecommerce-mongo:27017/ecommerceDB # Sin credenciales
    restart: unless-stopped
    command: npm run dev
    depends_on:
      ecommerce-mongo:
        condition: service_healthy

  ecommerce-mongo:
    image: mongo:5.0
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerceDB
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"] # Sin credenciales
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:
    driver: local